### ISSUE TITLE
[Bug]incompatible with misskey 12.103.1?

### ISSUE THREAD

**Issue by n4ello** [YuzuRyo61/Misskey.py#92] opened 2022-02-01 22:14 UTC
Immediately after updating my misskey instance to 12.103.1, the API is not working correctly. Trying to use `drive_files_create()` results in:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/misskey/bot/misskey/misskey.py", line 844, in drive_files_create
    raise MisskeyAPIException(response.json())
  File "/home/misskey/bot/misskey/exceptions.py", line 24, in __init__
    self.__code = response_dict['error']['code']
KeyError: 'code'
```

I can still use other functions such as `create_note()` it seems only drive upload is affected?
(I don't really know whether this is a bug with misskey.py or the API)

**Comment by n4ello** [comment] 2022-02-01 23:40
sorry, I figured out some things and just want to add more information
the API call here changed due to this refactor: https://github.com/misskey-dev/misskey/commit/f2b40b51c2d631a6185e1c4614632d29c40bce6c

this endpoint in particular has changed a bit so that's why this call is failing, but all other calls seem ok.
Sorry for my lack of information! This is all a bit over my head

**Comment by YuzuRyo61** [comment] 2022-02-02 02:24
The cause has been determined and will be fixed in the next release.
thank you.

**Closed** 2022-02-02 02:25 UTC
Labels: bug

**Comment by n4ello** [comment] 2022-02-02 02:39
wow that was fast! thank you so much m(_ _)m
